name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  docker_registory: docker.pkg.github.com

jobs:
  unit_test_a:
    name: Stub Unit Test A
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        docker build . -t testenv
        docker run --mount type=bind,src=$(pwd),dst=/fusebox testenv bash /fusebox/testkicker.sh
